.TH stcalc 1 2023-27-03
.SH NAME
stcalc \- Simple Terminal Calculator
.SH SYNOPSIS
.B stcalc
.RB [ OPTION ]
.RB [ EQUATION ]
.SH DESCRIPTION
.B stcalc
a simple command-line calculator written in C
.SH OPTIONS
.TP
.B \-h
prints help menu
.TP
.B \-i
interactive mode; prints to stdout
.SH USAGE
Improper Format: 
.B 1+2

Proper Format: 
.B 1 + 2

Use
.B x
instead of
.B *
for multiplication in non-interactive mode
.SH Author
Written by Madison Lynch <madi@mxdi.xyz>